// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YpenService.Helpers;

#nullable disable

namespace YpenService.Migrations
{
    [DbContext(typeof(YpenDbContext))]
    [Migration("20260605175014_FinalRegionTable")]
    partial class FinalRegionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YpenService.Models.Pollinator.Persistence.RegionUnits", b =>
                {
                    b.Property<string>("unit_KALCODE")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double>("unit_Area")
                        .HasColumnType("double precision");

                    b.Property<string>("unit_Center")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("unit_Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("unit_Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("unit_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Geometry>("unit_Shapes")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon, 4326)");

                    b.HasKey("unit_KALCODE");

                    b.ToTable("RegionUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
