// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YpenService.Helpers;

#nullable disable

namespace ForecastService.Migrations
{
    [DbContext(typeof(ForecastDbContext))]
    [Migration("20260728190708_DoubleToFloat")]
    partial class DoubleToFloat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForecastService.Models.Pollinator.DAOs.AirQualityDAO", b =>
                {
                    b.Property<DateOnly>("Time")
                        .HasColumnType("date")
                        .HasColumnName("Time");

                    b.Property<string>("Kalcode")
                        .HasColumnType("text");

                    b.Property<float>("AQI")
                        .HasColumnType("real")
                        .HasColumnName("AQI");

                    b.Property<float>("AlderPollen")
                        .HasColumnType("real")
                        .HasColumnName("AlderPollen");

                    b.Property<float>("BirchPollen")
                        .HasColumnType("real")
                        .HasColumnName("BirchPollen");

                    b.Property<float>("Dust")
                        .HasColumnType("real")
                        .HasColumnName("Dust");

                    b.Property<float>("GrassPollen")
                        .HasColumnType("real")
                        .HasColumnName("GrassPollen");

                    b.Property<float>("MugwortPollen")
                        .HasColumnType("real")
                        .HasColumnName("MugwortPollen");

                    b.Property<float>("NO2")
                        .HasColumnType("real")
                        .HasColumnName("NO2");

                    b.Property<float>("O3")
                        .HasColumnType("real")
                        .HasColumnName("O3");

                    b.Property<float>("OlivePollen")
                        .HasColumnType("real")
                        .HasColumnName("OlivePollen");

                    b.Property<float>("PM10")
                        .HasColumnType("real")
                        .HasColumnName("PM10");

                    b.Property<float>("PM2_5")
                        .HasColumnType("real")
                        .HasColumnName("PM2_5");

                    b.Property<float>("RagweedPollen")
                        .HasColumnType("real")
                        .HasColumnName("RagweedPollen");

                    b.HasKey("Time", "Kalcode");

                    b.ToTable("AirQuality", (string)null);
                });

            modelBuilder.Entity("ForecastService.Models.Pollinator.DAOs.WeatherDAO", b =>
                {
                    b.Property<string>("Kalcode")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Time")
                        .HasColumnType("date")
                        .HasColumnName("Time");

                    b.Property<float>("Humidity")
                        .HasColumnType("real")
                        .HasColumnName("Humidity");

                    b.Property<float>("PrecipitationPct")
                        .HasColumnType("real")
                        .HasColumnName("Percipitation");

                    b.Property<float>("TemperatureMax")
                        .HasColumnType("real")
                        .HasColumnName("TemperatureMax");

                    b.Property<float>("TemperatureMin")
                        .HasColumnType("real")
                        .HasColumnName("TemperatureMin");

                    b.Property<float>("WindSpeed")
                        .HasColumnType("real")
                        .HasColumnName("WindSpeed");

                    b.Property<int>("WmoCode")
                        .HasColumnType("integer")
                        .HasColumnName("WmoCode");

                    b.HasKey("Kalcode", "Time");

                    b.ToTable("Weather", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
